version: '3'
services:
  proxy:
    build: proxy/
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - '80:80'
  frontend:
    build: frontend/
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '3000'
    stdin_open: true
  backend:
    build: backend/
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/ajando
      - PORT=3000
    ports:
      - '3000'
  mongo:
    image: 'mongo'
    volumes:
      - ./mongo/mongoVolume:/data/db
    ports:
      - '27017-2019'
